[project]
name = "simplerenv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "coacd>=1.0.7",
    "mani-skill>=3.0.0b21",
    "octo",
    "rlds>=0.1.8",
    "sapien>=3.0.0b1",
    "tensorflow-datasets>=4.9.9",
    "tensorflow-hub>=0.16.1",
    "tf-agents>=0.12.1",
    "simulated-annealing",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
simulated-annealing = { git = "https://github.com/nathanrooy/simulated-annealing" }
simpler_env = { workspace = true }
octo = { path = "./third_party/octo" }

[tool.uv.workspace]
members = ["."]
